services:
    security_right_context:
        class: Core\SecurityBundle\Context\RightContext
        arguments: [@service_container] 

    security_whitelist:
        class: Core\SecurityBundle\Context\WhiteList
        arguments: [%route_whitelist_anonymous%, %route_whitelist_user%]

    security_right_profiler:
        class: Core\SecurityBundle\Profiler\RightsCollector
        tags:
            -
                name: data_collector
                template: CoreSecurityBundle:Profiler:secure.collector.html.twig
                id: rights
    
    some_annotation_driver:
       class: Core\SecurityBundle\Annotations\Driver\AnnotationDriver
       tags: [{name: kernel.event_listener, event: kernel.controller, method: onKernelController}] #Point event
       arguments: [@annotation_reader,@service_container,object] # mozliwe opcje: object, module

    kernel.listener.access_denied:
        class: Core\SecurityBundle\EventListener\AccessDeniedListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        arguments: [@service_container] 