<?php

namespace Core\SecurityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectIdentityRepository extends EntityRepository
{

   
    
    public function findGroupRights($group)
    {

        $qb = $this->createQueryBuilder('objectidentity')
                ->select('objectidentity,right')
                ->leftJoin('Core\SecurityBundle\Entity\Right', 'right', 'WITH', 'right.objectidentity = objectidentity and right.group = :group')
                ->setParameter('group', $group);
        $result = $qb->getQuery()->getArrayResult();
        return $result;
    }

}
