<?php

namespace Core\SecurityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightRepository extends EntityRepository
{

   

}
